### ISSUE TITLE
Please upgrade library version

### ISSUE THREAD

**Issue by hellboy81** [TheKalin/jQuery-File-Upload.MVC5#2]
Please make compatible with last `jQuery-File-Upload` version

**Comment by TheKalin** [comment]
@hellboy81 Sadly, i don't maintain this repo any more.  Feel free to create PR.

**Comment by hellboy81** [comment]
@LeeDumond @TheKalin  Can you provide answer on [this question](https://stackoverflow.com/questions/45418479/empty-template-download-result-after-succesfull-file-upload)

I have trouble with 2 multple instances on page
