### ISSUE TITLE
Problem with Visual studio 2015

### ISSUE THREAD

**Issue by Bonaldal** [TheKalin/jQuery-File-Upload.MVC5#3]
Hello,

If i test this project with Visual studio 2015 :
After adding files, when i click on button 'Start', the page is reloading and the image disappears
On the other hand it works well with visual studio 2013. Do you have an idea?

Thank you

**Comment by samseen** [comment]
I use VS 2015 to run it and it works fine. Can you share a snapshot of the process?

**Comment by Bonaldal** [comment]
I have Browser Link activated in my visual studio 2015. The problem comes from him. If I disable it everything works.
