### ISSUE TITLE
Delete thumb

### ISSUE THREAD

**Issue by JoeTseng** [TheKalin/jQuery-File-Upload.MVC5#6]
In FilesHelper.cs line 61.
I suggest changing
`String partThumb2 = Path.Combine(partThumb1, file + "80x80.jpg");`
to
`String partThumb2 = Path.Combine(partThumb1, Path.GetFileNameWithoutExtension(file) + "80x80.jpg");`
Otherwise it will not be delete.

**Comment by TheKalin** [comment]
Feel free to create PR :)

**Comment by JoeTseng** [comment]
Thanks your code. Help me a lot. I will try to do it one day. XD
:+1:
